/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package replacer;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileFilter;
import java.util.Locale;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileView;

/**
 *
 * @author Cheke
 */
public class Replacer extends javax.swing.JFrame {

    String nombreArchivo;
    Reemplazador r = new Reemplazador();
    private int contador;
    private int contadorMensajes;

    /**
     * Creates new form Replacer
     */
    public Replacer() {

        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLocationRelativeTo(null);
        selectorFichero = new javax.swing.JFileChooser();
        selectorFichero = new javax.swing.JFileChooser();
        acercaDeReplacer = new javax.swing.JFrame();
        iconoApp = new javax.swing.JLabel();
        replacer = new javax.swing.JLabel();
        creador = new javax.swing.JLabel();
        imagenCC = new javax.swing.JLabel();
        licencia = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        primerCampo = new javax.swing.JLabel();
        segundoCampo = new javax.swing.JLabel();
        tercerCampo = new javax.swing.JLabel();
        cuartoCampo = new javax.swing.JLabel();
        quintoCampo = new javax.swing.JLabel();
        sextoCampo = new javax.swing.JLabel();
        septimoCampo = new javax.swing.JLabel();
        octavoCampo = new javax.swing.JLabel();
        novenoCampo = new javax.swing.JLabel();
        decimoCampo = new javax.swing.JLabel();
        unoIzquierda = new javax.swing.JTextField();
        dosIzquierda = new javax.swing.JTextField();
        tresIzquierda = new javax.swing.JTextField();
        cuatroIzquierda = new javax.swing.JTextField();
        cincoIzquierda = new javax.swing.JTextField();
        seisIzquierda = new javax.swing.JTextField();
        sieteIzquierda = new javax.swing.JTextField();
        ochoIzquierda = new javax.swing.JTextField();
        nueveIzquierda = new javax.swing.JTextField();
        diezIzquierda = new javax.swing.JTextField();
        unoDerecha = new javax.swing.JTextField();
        dosDerecha = new javax.swing.JTextField();
        tresDerecha = new javax.swing.JTextField();
        cuatroDerecha = new javax.swing.JTextField();
        cincoDerecha = new javax.swing.JTextField();
        seisDerecha = new javax.swing.JTextField();
        sieteDerecha = new javax.swing.JTextField();
        ochoDerecha = new javax.swing.JTextField();
        nueveDerecha = new javax.swing.JTextField();
        diezDerecha = new javax.swing.JTextField();
        reemplazar = new javax.swing.JButton();
        imagenReplacer = new javax.swing.JLabel();
        textoCargado = new javax.swing.JFormattedTextField();
        cargado = new javax.swing.JLabel();
        creado = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        textoCreado = new javax.swing.JFormattedTextField();
        separadorAbajo = new javax.swing.JSeparator();
        creacionTotal = new javax.swing.JLabel();
        etiquetaVacia = new javax.swing.JLabel();
        borrarTodo = new javax.swing.JToggleButton();
        Menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        cargar = new javax.swing.JMenuItem();
        separadorMenu = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        acercaDe = new javax.swing.JMenu();

        selectorFichero.setBackground(new java.awt.Color(255, 255, 255));
        selectorFichero.setCurrentDirectory(new java.io.File("C:\\"));
            selectorFichero.setDialogTitle("");
            selectorFichero.setFileHidingEnabled(true);
            selectorFichero.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
            selectorFichero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            selectorFichero.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

            acercaDeReplacer.setIconImage(getIconImage());
            acercaDeReplacer.setSize(new java.awt.Dimension(220, 240));

            iconoApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            iconoApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Iconopequeño.png"))); // NOI18N

            replacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/replacerblanco.png"))); // NOI18N

            creador.setText("Aplicación creada por Koutei_Cheke.");

            imagenCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/by-nc.eu_petit.png"))); // NOI18N

            licencia.setText("Bajo licencia Creative Commons.");

            version.setText("Versión v0.01a");

            setLocationRelativeTo(null);

            javax.swing.GroupLayout acercaDeReplacerLayout = new javax.swing.GroupLayout(acercaDeReplacer.getContentPane());
            acercaDeReplacer.getContentPane().setLayout(acercaDeReplacerLayout);
            acercaDeReplacerLayout.setHorizontalGroup(
                acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(licencia))
                                .addComponent(creador)
                                .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(version)
                                    .addGap(55, 55, 55)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                            .addGroup(acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                                    .addComponent(replacer)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                                    .addGap(0, 8, Short.MAX_VALUE)
                                    .addComponent(iconoApp)
                                    .addGap(18, 18, 18)
                                    .addComponent(imagenCC)))
                            .addContainerGap())))
            );
            acercaDeReplacerLayout.setVerticalGroup(
                acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acercaDeReplacerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(replacer, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(creador)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(licencia)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(version)
                    .addGap(18, 18, 18)
                    .addGroup(acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imagenCC)
                        .addComponent(iconoApp))
                    .addContainerGap(23, Short.MAX_VALUE))
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Replacer · v0.01a");
            setIconImage(getIconImage());
            setResizable(false);
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    formWindowClosing(evt);
                }
            });

            primerCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            primerCampo.setText("Primer campo:");

            segundoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            segundoCampo.setText("Segundo campo:");

            tercerCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            tercerCampo.setText("Tercer campo:");

            cuartoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            cuartoCampo.setText("Cuarto campo:");

            quintoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            quintoCampo.setText("Quinto campo:");

            sextoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            sextoCampo.setText("Sexto campo:");

            septimoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            septimoCampo.setText("Séptimo campo:");

            octavoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            octavoCampo.setText("Octavo campo:");

            novenoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            novenoCampo.setText("Noveno campo:");

            decimoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            decimoCampo.setText("Décimo campo:");

            reemplazar.setText("Reemplazar");
            reemplazar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    reemplazarActionPerformed(evt);
                }
            });

            imagenReplacer.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
            imagenReplacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/replacer.png"))); // NOI18N

            textoCargado.setEditable(false);

            cargado.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            cargado.setText("Archivo cargado:");

            creado.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
            creado.setText("Archivo automático:");

            textoCreado.setEditable(false);

            etiquetaVacia.setText(" ");

            borrarTodo.setText("Borrar todo");
            borrarTodo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    borrarTodoActionPerformed(evt);
                }
            });

            archivo.setText("Archivo");

            cargar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
            cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reply.png"))); // NOI18N
            cargar.setText("Cargar archivo");
            cargar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cargarActionPerformed(evt);
                }
            });
            archivo.add(cargar);
            archivo.add(separadorMenu);

            salir.setText("Salir");
            salir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    salirActionPerformed(evt);
                }
            });
            archivo.add(salir);

            Menu.add(archivo);

            acercaDe.setText("Acerca de");
            acercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    acercaDeMouseClicked(evt);
                }
            });
            acercaDe.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    acercaDeActionPerformed(evt);
                }
            });
            Menu.add(acercaDe);

            setJMenuBar(Menu);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(separador)
                        .addComponent(separadorAbajo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(borrarTodo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reemplazar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tercerCampo)
                                .addComponent(cuartoCampo)
                                .addComponent(quintoCampo)
                                .addComponent(sextoCampo)
                                .addComponent(septimoCampo)
                                .addComponent(octavoCampo)
                                .addComponent(novenoCampo)
                                .addComponent(decimoCampo)
                                .addComponent(primerCampo)
                                .addComponent(segundoCampo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tresIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(unoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dosIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cuatroIzquierda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ochoIzquierda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nueveIzquierda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(diezIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sieteIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cincoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seisIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(unoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dosDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tresDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cuatroDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cincoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ochoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nueveDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(diezDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sieteDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seisDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 16, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cargado)
                                .addComponent(creado)
                                .addComponent(etiquetaVacia))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textoCreado)
                                .addComponent(textoCargado, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imagenReplacer)
                                        .addComponent(creacionTotal))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(imagenReplacer)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoCargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cargado))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(creado)
                        .addComponent(textoCreado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(creacionTotal)
                        .addComponent(etiquetaVacia))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(primerCampo)
                        .addComponent(unoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(segundoCampo)
                        .addComponent(dosIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dosDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tercerCampo)
                        .addComponent(tresIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tresDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cuartoCampo)
                        .addComponent(cuatroIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cuatroDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quintoCampo)
                        .addComponent(cincoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cincoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sextoCampo)
                        .addComponent(seisIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seisDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(septimoCampo)
                        .addComponent(sieteIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sieteDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(octavoCampo)
                        .addComponent(ochoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ochoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(novenoCampo)
                        .addComponent(nueveIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nueveDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(decimoCampo)
                        .addComponent(diezIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(diezDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(separadorAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(reemplazar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrarTodo))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivo() {
        if (getContador() == 0) {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Advanced Substation Alpha (.ass)", "ass");
            selectorFichero.addChoosableFileFilter(filter);
            selectorFichero.addChoosableFileFilter(new FileNameExtensionFilter("Texto plano (.txt, .log, .ini)", "txt", "log", "ini"));
            selectorFichero.addChoosableFileFilter(new FileNameExtensionFilter("Archivo Koutei_Cheke (.kc)", "kc"));
            selectorFichero.setFileFilter(filter);
            selectorFichero.setAcceptAllFileFilterUsed(true);
        } else {
            contador++;
        }
        int seleccion = selectorFichero.showOpenDialog(Menu); //Abrimos el JFileChooser y guardamos el resultado en seleccion
        if (seleccion == JFileChooser.APPROVE_OPTION) { //Si el usuario ha pulsado la opción Aceptar
            File fichero = selectorFichero.getSelectedFile(); //Guardamos en la variable fichero el archivo seleccionado
            textoCargado.setValue(fichero.getName());
            nombreArchivo = fichero.getAbsolutePath();
            textoCreado.setValue(fichero.getName() + ".kc");
        }
    }

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        cargarArchivo();
        contador++;
    }//GEN-LAST:event_cargarActionPerformed

    private void reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reemplazarActionPerformed
        if (nombreArchivo == null) {
            creacionTotal.setText("¡No has cargado nada!");
        } else {
            r.reemplazar(nombreArchivo,
                    unoIzquierda.getText(), unoDerecha.getText(),
                    dosIzquierda.getText(), dosDerecha.getText(),
                    tresIzquierda.getText(), tresDerecha.getText(),
                    cuatroIzquierda.getText(), cuatroDerecha.getText(),
                    cincoIzquierda.getText(), cincoDerecha.getText(),
                    seisIzquierda.getText(), seisDerecha.getText(),
                    sieteIzquierda.getText(), sieteDerecha.getText(),
                    ochoIzquierda.getText(), ochoDerecha.getText(),
                    nueveIzquierda.getText(), nueveDerecha.getText(),
                    diezIzquierda.getText(), diezDerecha.getText());
            if (contadorMensajes % 2 == 0) {
                creacionTotal.setText("¡El archivo se ha creado con éxito!");
                contadorMensajes++;
            } else if (contadorMensajes % 7 == 0) {
                creacionTotal.setText("¡Buen trabajo!");
                contadorMensajes++;
            } else {
                creacionTotal.setText("¡Vas por buen camino!");
                contadorMensajes++;
            }
        }
    }//GEN-LAST:event_reemplazarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void acercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaDeMouseClicked
       acercaDeReplacer.setLocationRelativeTo(null);
       acercaDeReplacer.setVisible(true);
    }//GEN-LAST:event_acercaDeMouseClicked

    private void acercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeActionPerformed
       acercaDeReplacer.setLocationRelativeTo(null);
       acercaDeReplacer.setVisible(true);
    }//GEN-LAST:event_acercaDeActionPerformed

    private void borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTodoActionPerformed
        unoIzquierda.setText("");
        dosIzquierda.setText("");
        tresIzquierda.setText("");
        cuatroIzquierda.setText("");
        cincoIzquierda.setText("");
        seisIzquierda.setText("");
        sieteIzquierda.setText("");
        ochoIzquierda.setText("");
        nueveIzquierda.setText("");
        diezIzquierda.setText("");
        unoDerecha.setText("");
        dosDerecha.setText("");
        tresDerecha.setText("");
        cuatroDerecha.setText("");
        cincoDerecha.setText("");
        seisDerecha.setText("");
        sieteDerecha.setText("");
        ochoDerecha.setText("");
        nueveDerecha.setText("");
        diezDerecha.setText("");
    }//GEN-LAST:event_borrarTodoActionPerformed

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("resources/Icono.png"));

        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {

            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (Exception e) {
            //e.printStackTrace();
        }
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Replacer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu acercaDe;
    private javax.swing.JFrame acercaDeReplacer;
    private javax.swing.JMenu archivo;
    private javax.swing.JToggleButton borrarTodo;
    private javax.swing.JLabel cargado;
    private javax.swing.JMenuItem cargar;
    private javax.swing.JTextField cincoDerecha;
    private javax.swing.JTextField cincoIzquierda;
    private javax.swing.JLabel creacionTotal;
    private javax.swing.JLabel creado;
    private javax.swing.JLabel creador;
    private javax.swing.JLabel cuartoCampo;
    private javax.swing.JTextField cuatroDerecha;
    private javax.swing.JTextField cuatroIzquierda;
    private javax.swing.JLabel decimoCampo;
    private javax.swing.JTextField diezDerecha;
    private javax.swing.JTextField diezIzquierda;
    private javax.swing.JTextField dosDerecha;
    private javax.swing.JTextField dosIzquierda;
    private javax.swing.JLabel etiquetaVacia;
    private javax.swing.JLabel iconoApp;
    private javax.swing.JLabel imagenCC;
    private javax.swing.JLabel imagenReplacer;
    private javax.swing.JLabel licencia;
    private javax.swing.JLabel novenoCampo;
    private javax.swing.JTextField nueveDerecha;
    private javax.swing.JTextField nueveIzquierda;
    private javax.swing.JTextField ochoDerecha;
    private javax.swing.JTextField ochoIzquierda;
    private javax.swing.JLabel octavoCampo;
    private javax.swing.JLabel primerCampo;
    private javax.swing.JLabel quintoCampo;
    private javax.swing.JButton reemplazar;
    private javax.swing.JLabel replacer;
    private javax.swing.JMenuItem salir;
    private javax.swing.JLabel segundoCampo;
    private javax.swing.JTextField seisDerecha;
    private javax.swing.JTextField seisIzquierda;
    private javax.swing.JFileChooser selectorFichero;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separadorAbajo;
    private javax.swing.JPopupMenu.Separator separadorMenu;
    private javax.swing.JLabel septimoCampo;
    private javax.swing.JLabel sextoCampo;
    private javax.swing.JTextField sieteDerecha;
    private javax.swing.JTextField sieteIzquierda;
    private javax.swing.JLabel tercerCampo;
    private javax.swing.JFormattedTextField textoCargado;
    private javax.swing.JFormattedTextField textoCreado;
    private javax.swing.JTextField tresDerecha;
    private javax.swing.JTextField tresIzquierda;
    private javax.swing.JTextField unoDerecha;
    private javax.swing.JTextField unoIzquierda;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables

    public int getContador() {
        return contador;
    }

    public void setContador(int contador) {
        this.contador = contador;
    }
}
