/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package replacer;

import java.awt.*;
import java.io.*;
import java.net.*;
import javax.swing.*;
import javax.swing.filechooser.*;

/**
 *
 * @author Cheke
 */
public class Replacer extends javax.swing.JFrame {

    String nombreArchivo;
    Reemplazador r = new Reemplazador();
    private int contador;
    private int contadorMensajes;
    

    /**
     * Creates new form Replacer
     */
    public Replacer() {

        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorFicheroCargado = new javax.swing.JFileChooser();
        selectorFicheroGuardado = new javax.swing.JFileChooser();
        acercaDeReplacer = new javax.swing.JFrame();
        iconoApp = new javax.swing.JLabel();
        replacer = new javax.swing.JLabel();
        creador = new javax.swing.JLabel();
        imagenCC = new javax.swing.JLabel();
        licencia = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        barraGrupo = new javax.swing.ButtonGroup();
        primerCampo = new javax.swing.JLabel();
        segundoCampo = new javax.swing.JLabel();
        tercerCampo = new javax.swing.JLabel();
        cuartoCampo = new javax.swing.JLabel();
        quintoCampo = new javax.swing.JLabel();
        sextoCampo = new javax.swing.JLabel();
        septimoCampo = new javax.swing.JLabel();
        octavoCampo = new javax.swing.JLabel();
        novenoCampo = new javax.swing.JLabel();
        decimoCampo = new javax.swing.JLabel();
        unoIzquierda = new javax.swing.JTextField();
        dosIzquierda = new javax.swing.JTextField();
        tresIzquierda = new javax.swing.JTextField();
        cuatroIzquierda = new javax.swing.JTextField();
        cincoIzquierda = new javax.swing.JTextField();
        seisIzquierda = new javax.swing.JTextField();
        sieteIzquierda = new javax.swing.JTextField();
        ochoIzquierda = new javax.swing.JTextField();
        nueveIzquierda = new javax.swing.JTextField();
        diezIzquierda = new javax.swing.JTextField();
        unoDerecha = new javax.swing.JTextField();
        dosDerecha = new javax.swing.JTextField();
        tresDerecha = new javax.swing.JTextField();
        cuatroDerecha = new javax.swing.JTextField();
        cincoDerecha = new javax.swing.JTextField();
        seisDerecha = new javax.swing.JTextField();
        sieteDerecha = new javax.swing.JTextField();
        ochoDerecha = new javax.swing.JTextField();
        nueveDerecha = new javax.swing.JTextField();
        diezDerecha = new javax.swing.JTextField();
        reemplazar = new javax.swing.JButton();
        imagenReplacer = new javax.swing.JLabel();
        textoCargado = new javax.swing.JFormattedTextField();
        cargado = new javax.swing.JLabel();
        creado = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        textoCreado = new javax.swing.JFormattedTextField();
        separadorAbajo = new javax.swing.JSeparator();
        creacionTotal = new javax.swing.JLabel();
        etiquetaVacia = new javax.swing.JLabel();
        borrarTodo = new javax.swing.JToggleButton();
        barra = new javax.swing.JToolBar();
        nuevo = new javax.swing.JButton();
        cargarBarra = new javax.swing.JButton();
        guardarBarra = new javax.swing.JButton();
        campoUno = new javax.swing.JButton();
        campoDos = new javax.swing.JButton();
        campoTres = new javax.swing.JButton();
        campoCuatro = new javax.swing.JButton();
        campoCinco = new javax.swing.JButton();
        campoSeis = new javax.swing.JButton();
        campoSiete = new javax.swing.JButton();
        campoOcho = new javax.swing.JButton();
        campoNueve = new javax.swing.JButton();
        campoDiez = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        nuevoMenu = new javax.swing.JMenuItem();
        cargar = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        guardarComo = new javax.swing.JMenuItem();
        separadorMenu = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        acercaDe = new javax.swing.JMenu();
        contenido = new javax.swing.JMenuItem();
        separadorMenu2 = new javax.swing.JPopupMenu.Separator();
        acercaDeMenu = new javax.swing.JMenuItem();

        selectorFicheroCargado.setApproveButtonText("Cargar");
        selectorFicheroCargado.setBackground(new java.awt.Color(240, 240, 240));
        selectorFicheroCargado.setDialogTitle("");
        selectorFicheroCargado.setFileHidingEnabled(true);
        selectorFicheroCargado.setToolTipText("");
        selectorFicheroCargado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selectorFicheroCargado.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        selectorFicheroCargado.setName(""); // NOI18N

        selectorFicheroGuardado.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        selectorFicheroGuardado.setCurrentDirectory(new java.io.File("C:\\Program Files\\NetBeans 8.0.2\\<user code>"));
        selectorFicheroGuardado.setFileHidingEnabled(true);
        selectorFicheroGuardado.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        selectorFicheroGuardado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        acercaDeReplacer.setIconImage(getIconImage());
        acercaDeReplacer.setResizable(false);

        iconoApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Iconopequeño.png"))); // NOI18N

        replacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/replacerblanco.png"))); // NOI18N

        creador.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        creador.setText("Aplicación creada por Koutei_Cheke.");

        imagenCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/by-nc.eu_petit.png"))); // NOI18N

        licencia.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        licencia.setText("Bajo licencia Creative Commons.");

        version.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        version.setText("Versión v0.03a");

        setLocationRelativeTo(null);

        javax.swing.GroupLayout acercaDeReplacerLayout = new javax.swing.GroupLayout(acercaDeReplacer.getContentPane());
        acercaDeReplacer.getContentPane().setLayout(acercaDeReplacerLayout);
        acercaDeReplacerLayout.setHorizontalGroup(
            acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                        .addComponent(replacer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iconoApp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenCC)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                        .addGroup(acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(licencia))
                            .addComponent(creador)
                            .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(version)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        acercaDeReplacerLayout.setVerticalGroup(
            acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acercaDeReplacerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(replacer, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(version)
                .addGap(18, 18, 18)
                .addGroup(acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenCC)
                    .addComponent(iconoApp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Replacer · v0.03a");
        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        primerCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        primerCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_1_black_18px.png"))); // NOI18N

        segundoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        segundoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_2_black_18px.png"))); // NOI18N

        tercerCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tercerCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_3_black_18px.png"))); // NOI18N

        cuartoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cuartoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_4_black_18px.png"))); // NOI18N

        quintoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        quintoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_5_black_18px.png"))); // NOI18N

        sextoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        sextoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_6_black_18px.png"))); // NOI18N

        septimoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        septimoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_7_black_18px.png"))); // NOI18N

        octavoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        octavoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_8_black_18px.png"))); // NOI18N

        novenoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        novenoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_9_black_18px.png"))); // NOI18N

        decimoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        decimoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_10_black_18px.png"))); // NOI18N

        reemplazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_autorenew_black_18dp.png"))); // NOI18N
        reemplazar.setToolTipText("Reemplazar");
        reemplazar.setBorder(null);
        reemplazar.setBorderPainted(false);
        reemplazar.setContentAreaFilled(false);
        reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reemplazarActionPerformed(evt);
            }
        });

        imagenReplacer.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        imagenReplacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/replacer.png"))); // NOI18N

        textoCargado.setEditable(false);

        cargado.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cargado.setText("Archivo cargado:");

        creado.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        creado.setText("Archivo automático:");

        textoCreado.setEditable(false);

        etiquetaVacia.setText(" ");

        borrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_highlight_off_black_18dp.png"))); // NOI18N
        borrarTodo.setToolTipText("Borrar todo");
        borrarTodo.setBorder(null);
        borrarTodo.setBorderPainted(false);
        borrarTodo.setContentAreaFilled(false);
        borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTodoActionPerformed(evt);
            }
        });

        barra.setFloatable(false);
        barra.setRollover(true);

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_insert_drive_file_black_18px.png"))); // NOI18N
        nuevo.setToolTipText("Borrar todo");
        nuevo.setBorderPainted(false);
        nuevo.setContentAreaFilled(false);
        nuevo.setFocusable(false);
        nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        barra.add(nuevo);

        cargarBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_unarchive_black_20px.png"))); // NOI18N
        cargarBarra.setToolTipText("Cargar");
        cargarBarra.setBorderPainted(false);
        cargarBarra.setContentAreaFilled(false);
        cargarBarra.setFocusable(false);
        cargarBarra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cargarBarra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cargarBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarBarraActionPerformed(evt);
            }
        });
        barra.add(cargarBarra);

        guardarBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_archive_black_20px.png"))); // NOI18N
        guardarBarra.setToolTipText("Guardar");
        guardarBarra.setBorderPainted(false);
        guardarBarra.setContentAreaFilled(false);
        guardarBarra.setEnabled(false);
        guardarBarra.setFocusable(false);
        guardarBarra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarBarra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardarBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBarraActionPerformed(evt);
            }
        });
        barra.add(guardarBarra);

        campoUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoUno.setBorder(null);
        campoUno.setBorderPainted(false);
        campoUno.setContentAreaFilled(false);
        campoUno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoUno.setFocusPainted(false);
        campoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUnoActionPerformed(evt);
            }
        });

        campoDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoDos.setBorder(null);
        campoDos.setBorderPainted(false);
        campoDos.setContentAreaFilled(false);
        campoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDosActionPerformed(evt);
            }
        });

        campoTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoTres.setBorder(null);
        campoTres.setBorderPainted(false);
        campoTres.setContentAreaFilled(false);
        campoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTresActionPerformed(evt);
            }
        });

        campoCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoCuatro.setBorder(null);
        campoCuatro.setBorderPainted(false);
        campoCuatro.setContentAreaFilled(false);
        campoCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCuatroActionPerformed(evt);
            }
        });

        campoCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoCinco.setBorder(null);
        campoCinco.setBorderPainted(false);
        campoCinco.setContentAreaFilled(false);
        campoCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCincoActionPerformed(evt);
            }
        });

        campoSeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoSeis.setBorder(null);
        campoSeis.setBorderPainted(false);
        campoSeis.setContentAreaFilled(false);
        campoSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSeisActionPerformed(evt);
            }
        });

        campoSiete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoSiete.setBorder(null);
        campoSiete.setBorderPainted(false);
        campoSiete.setContentAreaFilled(false);
        campoSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSieteActionPerformed(evt);
            }
        });

        campoOcho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoOcho.setBorder(null);
        campoOcho.setBorderPainted(false);
        campoOcho.setContentAreaFilled(false);
        campoOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoOchoActionPerformed(evt);
            }
        });

        campoNueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoNueve.setBorder(null);
        campoNueve.setBorderPainted(false);
        campoNueve.setContentAreaFilled(false);
        campoNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNueveActionPerformed(evt);
            }
        });

        campoDiez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoDiez.setBorder(null);
        campoDiez.setBorderPainted(false);
        campoDiez.setContentAreaFilled(false);
        campoDiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDiezActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Buscar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Reemplazar");

        archivo.setText("Archivo");

        nuevoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nuevoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_insert_drive_file_black_15px.png"))); // NOI18N
        nuevoMenu.setText("Nuevo archivo");
        nuevoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuActionPerformed(evt);
            }
        });
        archivo.add(nuevoMenu);

        cargar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_unarchive_black_15px.png"))); // NOI18N
        cargar.setText("Cargar archivo");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });
        archivo.add(cargar);

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_archive_black_15px.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.setEnabled(false);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        archivo.add(guardar);

        guardarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        guardarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_saveas_black_15px.png"))); // NOI18N
        guardarComo.setText("Guardar como...");
        guardarComo.setEnabled(false);
        guardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarComoActionPerformed(evt);
            }
        });
        archivo.add(guardarComo);
        archivo.add(separadorMenu);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        archivo.add(salir);

        Menu.add(archivo);

        acercaDe.setText("Ayuda");

        contenido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        contenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_help_black_18px.png"))); // NOI18N
        contenido.setText("Contenido");
        contenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contenidoActionPerformed(evt);
            }
        });
        acercaDe.add(contenido);
        acercaDe.add(separadorMenu2);

        acercaDeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_copyright_black_18px.png"))); // NOI18N
        acercaDeMenu.setText("Acerca de");
        acercaDeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeMenuActionPerformed(evt);
            }
        });
        acercaDe.add(acercaDeMenu);

        Menu.add(acercaDe);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(borrarTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagenReplacer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reemplazar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separador)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cargado)
                                    .addComponent(creado)
                                    .addComponent(etiquetaVacia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCargado)
                                    .addComponent(textoCreado)
                                    .addComponent(creacionTotal)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separadorAbajo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(primerCampo, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(segundoCampo, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(tercerCampo, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(cuartoCampo, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(quintoCampo, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(sextoCampo, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(septimoCampo, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(octavoCampo, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(novenoCampo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(decimoCampo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tresIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(unoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dosIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cuatroIzquierda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ochoIzquierda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nueveIzquierda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(diezIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sieteIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cincoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seisIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(unoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dosDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tresDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cuatroDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cincoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ochoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nueveDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(diezDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sieteDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seisDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoUno)
                                            .addComponent(campoDos)
                                            .addComponent(campoTres)
                                            .addComponent(campoCuatro)
                                            .addComponent(campoCinco)
                                            .addComponent(campoSeis)
                                            .addComponent(campoSiete)
                                            .addComponent(campoOcho)
                                            .addComponent(campoNueve)
                                            .addComponent(campoDiez)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(56, 56, 56)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creado)
                    .addComponent(textoCreado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creacionTotal)
                    .addComponent(etiquetaVacia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primerCampo)
                            .addComponent(unoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoUno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(segundoCampo)
                                .addComponent(dosIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoDos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tercerCampo)
                            .addComponent(tresIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuartoCampo)
                            .addComponent(cuatroIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCuatro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quintoCampo)
                            .addComponent(cincoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCinco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sextoCampo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(seisIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoSeis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(septimoCampo)
                            .addComponent(sieteIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoSiete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(octavoCampo)
                            .addComponent(ochoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoOcho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(novenoCampo)
                                    .addComponent(nueveIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(decimoCampo)
                                    .addComponent(diezIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoNueve)
                                .addGap(8, 8, 8)
                                .addComponent(campoDiez)))
                        .addGap(18, 18, 18)
                        .addComponent(separadorAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dosDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tresDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuatroDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cincoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seisDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sieteDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ochoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nueveDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diezDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(borrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reemplazar))
                    .addComponent(imagenReplacer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivo() {
        if (getContador() == 0) {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Advanced Substation Alpha (.ass)", "ass");
            selectorFicheroCargado.addChoosableFileFilter(filter);
            selectorFicheroCargado.addChoosableFileFilter(new FileNameExtensionFilter("Texto plano (.txt, .log, .ini)", "txt", "log", "ini"));
            selectorFicheroCargado.addChoosableFileFilter(new FileNameExtensionFilter("Archivo Koutei_Cheke (.kc)", "kc"));
            selectorFicheroCargado.setFileFilter(filter);
            selectorFicheroCargado.setAcceptAllFileFilterUsed(true);
        } else {
            contador++;
        }
        int seleccion = selectorFicheroCargado.showOpenDialog(Menu); //Abrimos el JFileChooser y guardamos el resultado en seleccion

        setLocationRelativeTo(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) { //Si el usuario ha pulsado la opción Aceptar
            File fichero = selectorFicheroCargado.getSelectedFile(); //Guardamos en la variable fichero el archivo seleccionado
            textoCargado.setValue(fichero.getName());
            nombreArchivo = fichero.getAbsolutePath();
            textoCreado.setValue(fichero.getName() + ".kc");
        }
    }

    public void borrar() {
        unoIzquierda.setText("");
        dosIzquierda.setText("");
        tresIzquierda.setText("");
        cuatroIzquierda.setText("");
        cincoIzquierda.setText("");
        seisIzquierda.setText("");
        sieteIzquierda.setText("");
        ochoIzquierda.setText("");
        nueveIzquierda.setText("");
        diezIzquierda.setText("");
        unoDerecha.setText("");
        dosDerecha.setText("");
        tresDerecha.setText("");
        cuatroDerecha.setText("");
        cincoDerecha.setText("");
        seisDerecha.setText("");
        sieteDerecha.setText("");
        ochoDerecha.setText("");
        nueveDerecha.setText("");
        diezDerecha.setText("");
    }

    public void reemplazarArchivo() {
        if (nombreArchivo == null) {
            creacionTotal.setText("¡No has cargado nada!");
        } else {
            r.reemplazar(nombreArchivo,
                    unoIzquierda.getText(), unoDerecha.getText(),
                    dosIzquierda.getText(), dosDerecha.getText(),
                    tresIzquierda.getText(), tresDerecha.getText(),
                    cuatroIzquierda.getText(), cuatroDerecha.getText(),
                    cincoIzquierda.getText(), cincoDerecha.getText(),
                    seisIzquierda.getText(), seisDerecha.getText(),
                    sieteIzquierda.getText(), sieteDerecha.getText(),
                    ochoIzquierda.getText(), ochoDerecha.getText(),
                    nueveIzquierda.getText(), nueveDerecha.getText(),
                    diezIzquierda.getText(), diezDerecha.getText());
            if (contadorMensajes % 2 == 0) {
                creacionTotal.setText("¡El archivo se ha creado con éxito!");
                contadorMensajes++;
            } else if (contadorMensajes % 7 == 0) {
                creacionTotal.setText("¡Buen trabajo!");
                contadorMensajes++;
            } else {
                creacionTotal.setText("¡Vas por buen camino!");
                contadorMensajes++;
            }
        }
    }

    public void acercaDe() {
        acercaDeReplacer.setLocationRelativeTo(null);
        acercaDeReplacer.setVisible(true);
    }
    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        cargarArchivo();
        contador++;
    }//GEN-LAST:event_cargarActionPerformed

    private void reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reemplazarActionPerformed
        reemplazarArchivo();
    }//GEN-LAST:event_reemplazarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTodoActionPerformed
        borrar();
    }//GEN-LAST:event_borrarTodoActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        borrar();
    }//GEN-LAST:event_nuevoActionPerformed

    private void cargarBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarBarraActionPerformed
        cargarArchivo();
        contador++;
    }//GEN-LAST:event_cargarBarraActionPerformed

    private void campoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUnoActionPerformed
        unoIzquierda.setText("");
        unoDerecha.setText("");
    }//GEN-LAST:event_campoUnoActionPerformed

    private void campoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDosActionPerformed
        dosIzquierda.setText("");
        dosDerecha.setText("");
    }//GEN-LAST:event_campoDosActionPerformed

    private void campoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTresActionPerformed
        tresIzquierda.setText("");
        tresDerecha.setText("");
    }//GEN-LAST:event_campoTresActionPerformed

    private void campoCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCuatroActionPerformed
        cuatroIzquierda.setText("");
        cuatroDerecha.setText("");
    }//GEN-LAST:event_campoCuatroActionPerformed

    private void campoCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCincoActionPerformed
        cincoIzquierda.setText("");
        cincoDerecha.setText("");
    }//GEN-LAST:event_campoCincoActionPerformed

    private void campoSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSeisActionPerformed
        seisIzquierda.setText("");
        seisDerecha.setText("");    }//GEN-LAST:event_campoSeisActionPerformed

    private void campoSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSieteActionPerformed
        sieteIzquierda.setText("");
        sieteDerecha.setText("");    }//GEN-LAST:event_campoSieteActionPerformed

    private void campoOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoOchoActionPerformed
        ochoIzquierda.setText("");
        ochoDerecha.setText("");    }//GEN-LAST:event_campoOchoActionPerformed

    private void campoNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNueveActionPerformed
        nueveIzquierda.setText("");
        nueveDerecha.setText("");    }//GEN-LAST:event_campoNueveActionPerformed

    private void campoDiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDiezActionPerformed
        diezIzquierda.setText("");
        diezDerecha.setText("");    }//GEN-LAST:event_campoDiezActionPerformed

    private void acercaDeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeMenuActionPerformed
        acercaDe();
    }//GEN-LAST:event_acercaDeMenuActionPerformed

    private void nuevoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuActionPerformed
        borrar();
    }//GEN-LAST:event_nuevoMenuActionPerformed

    private void contenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contenidoActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            try {
                Desktop dk = Desktop.getDesktop();
                dk.browse(new URI("http://replacerblog.wordpress.com"));
            } catch (Exception ex) {
                System.out.println("Error al abrir URL: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_contenidoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void guardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarComoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarComoActionPerformed

    private void guardarBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBarraActionPerformed

    }//GEN-LAST:event_guardarBarraActionPerformed

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("resources/Icono.png"));

        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            // UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (Exception e) {
            //e.printStackTrace();
        }
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Replacer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu acercaDe;
    private javax.swing.JMenuItem acercaDeMenu;
    private javax.swing.JFrame acercaDeReplacer;
    private javax.swing.JMenu archivo;
    private javax.swing.JToolBar barra;
    private javax.swing.ButtonGroup barraGrupo;
    private javax.swing.JToggleButton borrarTodo;
    private javax.swing.JButton campoCinco;
    private javax.swing.JButton campoCuatro;
    private javax.swing.JButton campoDiez;
    private javax.swing.JButton campoDos;
    private javax.swing.JButton campoNueve;
    private javax.swing.JButton campoOcho;
    private javax.swing.JButton campoSeis;
    private javax.swing.JButton campoSiete;
    private javax.swing.JButton campoTres;
    private javax.swing.JButton campoUno;
    private javax.swing.JLabel cargado;
    private javax.swing.JMenuItem cargar;
    private javax.swing.JButton cargarBarra;
    private javax.swing.JTextField cincoDerecha;
    private javax.swing.JTextField cincoIzquierda;
    private javax.swing.JMenuItem contenido;
    private javax.swing.JLabel creacionTotal;
    private javax.swing.JLabel creado;
    private javax.swing.JLabel creador;
    private javax.swing.JLabel cuartoCampo;
    private javax.swing.JTextField cuatroDerecha;
    private javax.swing.JTextField cuatroIzquierda;
    private javax.swing.JLabel decimoCampo;
    private javax.swing.JTextField diezDerecha;
    private javax.swing.JTextField diezIzquierda;
    private javax.swing.JTextField dosDerecha;
    private javax.swing.JTextField dosIzquierda;
    private javax.swing.JLabel etiquetaVacia;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JButton guardarBarra;
    private javax.swing.JMenuItem guardarComo;
    private javax.swing.JLabel iconoApp;
    private javax.swing.JLabel imagenCC;
    private javax.swing.JLabel imagenReplacer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel licencia;
    private javax.swing.JLabel novenoCampo;
    private javax.swing.JTextField nueveDerecha;
    private javax.swing.JTextField nueveIzquierda;
    private javax.swing.JButton nuevo;
    private javax.swing.JMenuItem nuevoMenu;
    private javax.swing.JTextField ochoDerecha;
    private javax.swing.JTextField ochoIzquierda;
    private javax.swing.JLabel octavoCampo;
    private javax.swing.JLabel primerCampo;
    private javax.swing.JLabel quintoCampo;
    private javax.swing.JButton reemplazar;
    private javax.swing.JLabel replacer;
    private javax.swing.JMenuItem salir;
    private javax.swing.JLabel segundoCampo;
    private javax.swing.JTextField seisDerecha;
    private javax.swing.JTextField seisIzquierda;
    private javax.swing.JFileChooser selectorFicheroCargado;
    private javax.swing.JFileChooser selectorFicheroGuardado;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separadorAbajo;
    private javax.swing.JPopupMenu.Separator separadorMenu;
    private javax.swing.JPopupMenu.Separator separadorMenu2;
    private javax.swing.JLabel septimoCampo;
    private javax.swing.JLabel sextoCampo;
    private javax.swing.JTextField sieteDerecha;
    private javax.swing.JTextField sieteIzquierda;
    private javax.swing.JLabel tercerCampo;
    private javax.swing.JFormattedTextField textoCargado;
    private javax.swing.JFormattedTextField textoCreado;
    private javax.swing.JTextField tresDerecha;
    private javax.swing.JTextField tresIzquierda;
    private javax.swing.JTextField unoDerecha;
    private javax.swing.JTextField unoIzquierda;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables

    public int getContador() {
        return contador;
    }

    public void setContador(int contador) {
        this.contador = contador;
    }
}
