/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package replacer;

import java.awt.*;
import java.io.*;
import java.net.*;
import javax.swing.*;
import javax.swing.filechooser.*;

/**
 *
 * @author Cheke
 */
public class Replacer extends javax.swing.JFrame {

    String nombreArchivo;
    Reemplazador r = new Reemplazador();
    private int contador;
    private int contadorMensajes;

    /**
     * Creates new form Replacer
     */
    public Replacer() {

        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorFicheroCargado = new javax.swing.JFileChooser();
        acercaDeReplacer = new javax.swing.JFrame();
        iconoApp = new javax.swing.JLabel();
        replacer = new javax.swing.JLabel();
        creador = new javax.swing.JLabel();
        imagenCC = new javax.swing.JLabel();
        licencia = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        barraGrupo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        reemplazar = new javax.swing.JButton();
        textoCargado = new javax.swing.JFormattedTextField();
        cargado = new javax.swing.JLabel();
        creado = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        textoCreado = new javax.swing.JFormattedTextField();
        etiquetaVacia = new javax.swing.JLabel();
        borrarTodo = new javax.swing.JToggleButton();
        barra = new javax.swing.JToolBar();
        nuevo = new javax.swing.JButton();
        cargarBarra = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        imagenReplacer = new javax.swing.JLabel();
        interior = new javax.swing.JPanel();
        primerCampo = new javax.swing.JLabel();
        segundoCampo = new javax.swing.JLabel();
        tercerCampo = new javax.swing.JLabel();
        cuartoCampo = new javax.swing.JLabel();
        quintoCampo = new javax.swing.JLabel();
        sextoCampo = new javax.swing.JLabel();
        septimoCampo = new javax.swing.JLabel();
        octavoCampo = new javax.swing.JLabel();
        novenoCampo = new javax.swing.JLabel();
        decimoCampo = new javax.swing.JLabel();
        unoIzquierda = new javax.swing.JTextField();
        dosIzquierda = new javax.swing.JTextField();
        tresIzquierda = new javax.swing.JTextField();
        cuatroIzquierda = new javax.swing.JTextField();
        cincoIzquierda = new javax.swing.JTextField();
        seisIzquierda = new javax.swing.JTextField();
        sieteIzquierda = new javax.swing.JTextField();
        ochoIzquierda = new javax.swing.JTextField();
        nueveIzquierda = new javax.swing.JTextField();
        diezIzquierda = new javax.swing.JTextField();
        unoDerecha = new javax.swing.JTextField();
        dosDerecha = new javax.swing.JTextField();
        tresDerecha = new javax.swing.JTextField();
        cuatroDerecha = new javax.swing.JTextField();
        cincoDerecha = new javax.swing.JTextField();
        seisDerecha = new javax.swing.JTextField();
        sieteDerecha = new javax.swing.JTextField();
        ochoDerecha = new javax.swing.JTextField();
        nueveDerecha = new javax.swing.JTextField();
        diezDerecha = new javax.swing.JTextField();
        campoUno = new javax.swing.JButton();
        campoDos = new javax.swing.JButton();
        campoTres = new javax.swing.JButton();
        campoCuatro = new javax.swing.JButton();
        campoCinco = new javax.swing.JButton();
        campoSeis = new javax.swing.JButton();
        campoSiete = new javax.swing.JButton();
        campoOcho = new javax.swing.JButton();
        campoNueve = new javax.swing.JButton();
        campoDiez = new javax.swing.JButton();
        bajarUno = new javax.swing.JButton();
        subirUno = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        creacionTotal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        nuevoMenu = new javax.swing.JMenuItem();
        cargar = new javax.swing.JMenuItem();
        separadorMenu = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        acercaDe = new javax.swing.JMenu();
        contenido = new javax.swing.JMenuItem();
        separadorMenu2 = new javax.swing.JPopupMenu.Separator();
        acercaDeMenu = new javax.swing.JMenuItem();

        selectorFicheroCargado.setCurrentDirectory(new java.io.File("C:\\Program Files\\NetBeans 8.0.2\\<user code>"));
        selectorFicheroCargado.setFileHidingEnabled(true);
        selectorFicheroCargado.setAlignmentX(1.0F);
        selectorFicheroCargado.setAlignmentY(1.0F);
        selectorFicheroCargado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selectorFicheroCargado.setInheritsPopupMenu(true);
        selectorFicheroCargado.setMinimumSize(new java.awt.Dimension(551, 342));
        selectorFicheroCargado.setName("Elegir archivo a cargar..."); // NOI18N
        selectorFicheroCargado.setPreferredSize(new java.awt.Dimension(551, 342));

        acercaDeReplacer.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        acercaDeReplacer.setIconImage(getIconImage());
        acercaDeReplacer.setMinimumSize(new java.awt.Dimension(207, 223));
        acercaDeReplacer.setPreferredSize(new java.awt.Dimension(207, 223));
        acercaDeReplacer.setResizable(false);

        iconoApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Iconopequeño.png"))); // NOI18N

        replacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/replacerblanco.png"))); // NOI18N

        creador.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        creador.setText("Aplicación creada por Koutei_Cheke.");

        imagenCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/by-nc.eu_petit.png"))); // NOI18N

        licencia.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        licencia.setText("Bajo licencia Creative Commons.");

        version.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        version.setText("Versión v0.04a");

        setLocationRelativeTo(null);

        javax.swing.GroupLayout acercaDeReplacerLayout = new javax.swing.GroupLayout(acercaDeReplacer.getContentPane());
        acercaDeReplacer.getContentPane().setLayout(acercaDeReplacerLayout);
        acercaDeReplacerLayout.setHorizontalGroup(
            acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(replacer)
                    .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(iconoApp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagenCC))
                    .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(licencia))
                    .addComponent(creador)
                    .addGroup(acercaDeReplacerLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(version)))
                .addContainerGap())
        );
        acercaDeReplacerLayout.setVerticalGroup(
            acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acercaDeReplacerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(replacer, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(version)
                .addGap(18, 18, 18)
                .addGroup(acercaDeReplacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenCC)
                    .addComponent(iconoApp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Replacer · v0.04a");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(360, 350));
        setPreferredSize(new java.awt.Dimension(360, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        reemplazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_autorenew_black_18dp.png"))); // NOI18N
        reemplazar.setToolTipText("Reemplazar");
        reemplazar.setBorder(null);
        reemplazar.setBorderPainted(false);
        reemplazar.setContentAreaFilled(false);
        reemplazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reemplazar.setFocusPainted(false);
        reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reemplazarActionPerformed(evt);
            }
        });

        textoCargado.setEditable(false);

        cargado.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cargado.setText("Archivo cargado:");

        creado.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        creado.setText("Archivo automático:");

        textoCreado.setEditable(false);
        textoCreado.setText("Con extensión .kc");
        textoCreado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCreadoActionPerformed(evt);
            }
        });

        etiquetaVacia.setToolTipText("");
        etiquetaVacia.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                etiquetaVaciaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        borrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_delete_forever_black_48dp.png"))); // NOI18N
        borrarTodo.setToolTipText("Borrar todo");
        borrarTodo.setBorder(null);
        borrarTodo.setBorderPainted(false);
        borrarTodo.setContentAreaFilled(false);
        borrarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarTodo.setFocusPainted(false);
        borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTodoActionPerformed(evt);
            }
        });

        barra.setFloatable(false);
        barra.setRollover(true);

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_insert_drive_file_black_18px.png"))); // NOI18N
        nuevo.setToolTipText("Borrar todo");
        nuevo.setBorderPainted(false);
        nuevo.setContentAreaFilled(false);
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevo.setFocusable(false);
        nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        barra.add(nuevo);

        cargarBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_unarchive_black_20px.png"))); // NOI18N
        cargarBarra.setToolTipText("Cargar");
        cargarBarra.setBorderPainted(false);
        cargarBarra.setContentAreaFilled(false);
        cargarBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargarBarra.setFocusable(false);
        cargarBarra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cargarBarra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cargarBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarBarraActionPerformed(evt);
            }
        });
        barra.add(cargarBarra);

        imagenReplacer.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        imagenReplacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/replacer.png"))); // NOI18N
        imagenReplacer.setMinimumSize(new java.awt.Dimension(182, 70));

        primerCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        primerCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_1_black_18px.png"))); // NOI18N

        segundoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        segundoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_2_black_18px.png"))); // NOI18N

        tercerCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tercerCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_3_black_18px.png"))); // NOI18N

        cuartoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cuartoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_4_black_18px.png"))); // NOI18N

        quintoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        quintoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_5_black_18px.png"))); // NOI18N

        sextoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        sextoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_6_black_18px.png"))); // NOI18N

        septimoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        septimoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_7_black_18px.png"))); // NOI18N

        octavoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        octavoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_8_black_18px.png"))); // NOI18N

        novenoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        novenoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_9_black_18px.png"))); // NOI18N

        decimoCampo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        decimoCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_filter_10_black_18px.png"))); // NOI18N

        cuatroDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroDerechaActionPerformed(evt);
            }
        });

        campoUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoUno.setBorder(null);
        campoUno.setBorderPainted(false);
        campoUno.setContentAreaFilled(false);
        campoUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoUno.setFocusPainted(false);
        campoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUnoActionPerformed(evt);
            }
        });

        campoDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoDos.setBorder(null);
        campoDos.setBorderPainted(false);
        campoDos.setContentAreaFilled(false);
        campoDos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDosActionPerformed(evt);
            }
        });

        campoTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoTres.setBorder(null);
        campoTres.setBorderPainted(false);
        campoTres.setContentAreaFilled(false);
        campoTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTresActionPerformed(evt);
            }
        });

        campoCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoCuatro.setBorder(null);
        campoCuatro.setBorderPainted(false);
        campoCuatro.setContentAreaFilled(false);
        campoCuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCuatroActionPerformed(evt);
            }
        });

        campoCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoCinco.setBorder(null);
        campoCinco.setBorderPainted(false);
        campoCinco.setContentAreaFilled(false);
        campoCinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCincoActionPerformed(evt);
            }
        });

        campoSeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoSeis.setBorder(null);
        campoSeis.setBorderPainted(false);
        campoSeis.setContentAreaFilled(false);
        campoSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSeisActionPerformed(evt);
            }
        });

        campoSiete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoSiete.setBorder(null);
        campoSiete.setBorderPainted(false);
        campoSiete.setContentAreaFilled(false);
        campoSiete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSieteActionPerformed(evt);
            }
        });

        campoOcho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoOcho.setBorder(null);
        campoOcho.setBorderPainted(false);
        campoOcho.setContentAreaFilled(false);
        campoOcho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoOchoActionPerformed(evt);
            }
        });

        campoNueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoNueve.setBorder(null);
        campoNueve.setBorderPainted(false);
        campoNueve.setContentAreaFilled(false);
        campoNueve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNueveActionPerformed(evt);
            }
        });

        campoDiez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_backspace_black_18px.png"))); // NOI18N
        campoDiez.setBorder(null);
        campoDiez.setBorderPainted(false);
        campoDiez.setContentAreaFilled(false);
        campoDiez.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoDiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDiezActionPerformed(evt);
            }
        });

        bajarUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_add_box_black_20px.png"))); // NOI18N
        bajarUno.setBorder(null);
        bajarUno.setBorderPainted(false);
        bajarUno.setContentAreaFilled(false);
        bajarUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bajarUno.setFocusPainted(false);
        bajarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajarUnoActionPerformed(evt);
            }
        });

        subirUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_indeterminate_check_box_black_18px.png"))); // NOI18N
        subirUno.setBorder(null);
        subirUno.setBorderPainted(false);
        subirUno.setContentAreaFilled(false);
        subirUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subirUno.setFocusPainted(false);
        subirUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirUnoActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Buscar");
        jTextField1.setBorder(null);

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Reemplazar");
        jTextField2.setBorder(null);

        javax.swing.GroupLayout interiorLayout = new javax.swing.GroupLayout(interior);
        interior.setLayout(interiorLayout);
        interiorLayout.setHorizontalGroup(
            interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, interiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(interiorLayout.createSequentialGroup()
                        .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(segundoCampo)
                                .addGap(10, 10, 10)
                                .addComponent(dosIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(dosDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(tercerCampo)
                                .addGap(10, 10, 10)
                                .addComponent(tresIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(tresDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(cuartoCampo)
                                .addGap(10, 10, 10)
                                .addComponent(cuatroIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cuatroDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(quintoCampo)
                                .addGap(10, 10, 10)
                                .addComponent(cincoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cincoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(sextoCampo)
                                .addGap(10, 10, 10)
                                .addComponent(seisIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(seisDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(septimoCampo)
                                .addGap(10, 10, 10)
                                .addComponent(sieteIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(sieteDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(octavoCampo)
                                .addGap(10, 10, 10)
                                .addComponent(ochoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ochoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(novenoCampo)
                                .addGap(10, 10, 10)
                                .addComponent(nueveIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(nueveDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(decimoCampo)
                                .addGap(10, 10, 10)
                                .addComponent(diezIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(diezDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addComponent(primerCampo)
                                .addGap(10, 10, 10)
                                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unoIzquierda))
                                .addGap(10, 10, 10)
                                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unoDerecha))))
                        .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bajarUno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subirUno))
                            .addGroup(interiorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoDos)
                                    .addComponent(campoTres)
                                    .addComponent(campoCuatro)
                                    .addComponent(campoCinco)
                                    .addComponent(campoSeis)
                                    .addComponent(campoSiete)
                                    .addComponent(campoOcho)
                                    .addComponent(campoNueve)
                                    .addComponent(campoDiez)))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        interiorLayout.setVerticalGroup(
            interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, interiorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bajarUno)
                    .addComponent(subirUno)
                    .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primerCampo)
                    .addComponent(unoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(segundoCampo)
                    .addComponent(dosIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDos))
                .addGap(6, 6, 6)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tercerCampo)
                    .addComponent(tresIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tresDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTres))
                .addGap(6, 6, 6)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuartoCampo)
                    .addComponent(cuatroIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuatroDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCuatro))
                .addGap(6, 6, 6)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quintoCampo)
                    .addComponent(cincoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cincoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCinco))
                .addGap(6, 6, 6)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(interiorLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(sextoCampo))
                    .addComponent(seisIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seisDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSeis))
                .addGap(6, 6, 6)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(septimoCampo)
                    .addComponent(sieteIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sieteDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSiete))
                .addGap(6, 6, 6)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(octavoCampo)
                    .addComponent(ochoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ochoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoOcho))
                .addGap(6, 6, 6)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(novenoCampo)
                    .addComponent(nueveIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueveDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNueve))
                .addGap(6, 6, 6)
                .addGroup(interiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decimoCampo)
                    .addComponent(diezIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diezDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(interiorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(campoDiez)))
                .addContainerGap())
        );

        archivo.setText("Archivo");

        nuevoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nuevoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_insert_drive_file_black_15px.png"))); // NOI18N
        nuevoMenu.setText("Nuevo archivo");
        nuevoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuActionPerformed(evt);
            }
        });
        archivo.add(nuevoMenu);

        cargar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_unarchive_black_15px.png"))); // NOI18N
        cargar.setText("Cargar archivo");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });
        archivo.add(cargar);
        archivo.add(separadorMenu);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        archivo.add(salir);

        Menu.add(archivo);

        acercaDe.setText("Ayuda");

        contenido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        contenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_help_black_18px.png"))); // NOI18N
        contenido.setText("Contenido");
        contenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contenidoActionPerformed(evt);
            }
        });
        acercaDe.add(contenido);
        acercaDe.add(separadorMenu2);

        acercaDeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic_copyright_black_18px.png"))); // NOI18N
        acercaDeMenu.setText("Acerca de");
        acercaDeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeMenuActionPerformed(evt);
            }
        });
        acercaDe.add(acercaDeMenu);

        Menu.add(acercaDe);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargado)
                    .addComponent(creado))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creacionTotal)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoCreado, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(textoCargado))
                        .addGap(18, 18, 18)
                        .addComponent(reemplazar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(imagenReplacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separador)
                            .addComponent(etiquetaVacia)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenReplacer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cargado)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creado)
                            .addComponent(textoCreado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(borrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reemplazar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaVacia, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creacionTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Replacer · v0.04a");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivo() {

        if (getContador() == 0) {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Advanced Substation Alpha (.ass)", "ass");
            selectorFicheroCargado.addChoosableFileFilter(filter);
            selectorFicheroCargado.addChoosableFileFilter(new FileNameExtensionFilter("Texto plano (.txt, .log, .ini)", "txt", "log", "ini"));
            selectorFicheroCargado.addChoosableFileFilter(new FileNameExtensionFilter("Archivo Koutei_Cheke (.kc)", "kc"));
            selectorFicheroCargado.setFileFilter(filter);
            selectorFicheroCargado.setAcceptAllFileFilterUsed(true);
        } else {
            contador++;
        }
        int seleccion = selectorFicheroCargado.showOpenDialog(Menu); //Abrimos el JFileChooser y guardamos el resultado en seleccion
        
        if (seleccion == JFileChooser.APPROVE_OPTION) { //Si el usuario ha pulsado la opción Aceptar
            File fichero = selectorFicheroCargado.getSelectedFile(); //Guardamos en la variable fichero el archivo seleccionado
            textoCargado.setValue(fichero.getName());
            nombreArchivo = fichero.getAbsolutePath();
            textoCreado.setValue(fichero.getName() + ".kc");
        }
    }

    public void borrar() {
        unoIzquierda.setText("");
        dosIzquierda.setText("");
        tresIzquierda.setText("");
        cuatroIzquierda.setText("");
        cincoIzquierda.setText("");
        seisIzquierda.setText("");
        sieteIzquierda.setText("");
        ochoIzquierda.setText("");
        nueveIzquierda.setText("");
        diezIzquierda.setText("");
        unoDerecha.setText("");
        dosDerecha.setText("");
        tresDerecha.setText("");
        cuatroDerecha.setText("");
        cincoDerecha.setText("");
        seisDerecha.setText("");
        sieteDerecha.setText("");
        ochoDerecha.setText("");
        nueveDerecha.setText("");
        diezDerecha.setText("");
    }

    public void reemplazarArchivo() {
        if (nombreArchivo == null) {
            creacionTotal.setText("¡No has cargado nada!");
        } else {
            r.reemplazar(nombreArchivo,
                    unoIzquierda.getText(), unoDerecha.getText(),
                    dosIzquierda.getText(), dosDerecha.getText(),
                    tresIzquierda.getText(), tresDerecha.getText(),
                    cuatroIzquierda.getText(), cuatroDerecha.getText(),
                    cincoIzquierda.getText(), cincoDerecha.getText(),
                    seisIzquierda.getText(), seisDerecha.getText(),
                    sieteIzquierda.getText(), sieteDerecha.getText(),
                    ochoIzquierda.getText(), ochoDerecha.getText(),
                    nueveIzquierda.getText(), nueveDerecha.getText(),
                    diezIzquierda.getText(), diezDerecha.getText());
            if (contadorMensajes % 2 == 0) {
                creacionTotal.setText("¡El archivo se ha creado con éxito!");
                contadorMensajes++;
            } else if (contadorMensajes % 7 == 0) {
                creacionTotal.setText("¡Buen trabajo!");
                contadorMensajes++;
            } else {
                creacionTotal.setText("¡Vas por buen camino!");
                contadorMensajes++;
            }
        }
    }

    public void acercaDe() {
        acercaDeReplacer.setLocationRelativeTo(null);
        acercaDeReplacer.setVisible(true);
    }
    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        cargarArchivo();
        contador++;
    }//GEN-LAST:event_cargarActionPerformed

    private void reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reemplazarActionPerformed
        reemplazarArchivo();
    }//GEN-LAST:event_reemplazarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTodoActionPerformed
        borrar();
    }//GEN-LAST:event_borrarTodoActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        borrar();
    }//GEN-LAST:event_nuevoActionPerformed

    private void cargarBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarBarraActionPerformed
        cargarArchivo();
        contador++;
    }//GEN-LAST:event_cargarBarraActionPerformed

    private void campoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDosActionPerformed
        dosIzquierda.setText("");
        dosDerecha.setText("");
    }//GEN-LAST:event_campoDosActionPerformed

    private void campoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTresActionPerformed
        tresIzquierda.setText("");
        tresDerecha.setText("");
    }//GEN-LAST:event_campoTresActionPerformed

    private void campoCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCuatroActionPerformed
        cuatroIzquierda.setText("");
        cuatroDerecha.setText("");
    }//GEN-LAST:event_campoCuatroActionPerformed

    private void campoCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCincoActionPerformed
        cincoIzquierda.setText("");
        cincoDerecha.setText("");
    }//GEN-LAST:event_campoCincoActionPerformed

    private void campoSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSeisActionPerformed
        seisIzquierda.setText("");
        seisDerecha.setText("");    }//GEN-LAST:event_campoSeisActionPerformed

    private void campoSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSieteActionPerformed
        sieteIzquierda.setText("");
        sieteDerecha.setText("");    }//GEN-LAST:event_campoSieteActionPerformed

    private void campoOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoOchoActionPerformed
        ochoIzquierda.setText("");
        ochoDerecha.setText("");    }//GEN-LAST:event_campoOchoActionPerformed

    private void campoNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNueveActionPerformed
        nueveIzquierda.setText("");
        nueveDerecha.setText("");    }//GEN-LAST:event_campoNueveActionPerformed

    private void campoDiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDiezActionPerformed
        diezIzquierda.setText("");
        diezDerecha.setText("");    }//GEN-LAST:event_campoDiezActionPerformed

    private void acercaDeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeMenuActionPerformed
        acercaDe();
    }//GEN-LAST:event_acercaDeMenuActionPerformed

    private void nuevoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuActionPerformed
        borrar();
    }//GEN-LAST:event_nuevoMenuActionPerformed

    private void contenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contenidoActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            try {
                Desktop dk = Desktop.getDesktop();
                dk.browse(new URI("https://replacerblog.wordpress.com/2016/07/03/ayuda-para-replacer/"));
            } catch (Exception ex) {
                System.out.println("Error al abrir URL: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_contenidoActionPerformed

    private void campoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUnoActionPerformed
        unoIzquierda.setText("");
        unoDerecha.setText("");
    }//GEN-LAST:event_campoUnoActionPerformed

    private void bajarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajarUnoActionPerformed
        if (!campoDos.isVisible()) {
            campoDos.setVisible(true);
            segundoCampo.setVisible(true);
            dosIzquierda.setVisible(true);
            dosDerecha.setVisible(true);
            setSize(360, 375);
        } else if (!campoTres.isVisible()) {
            campoTres.setVisible(true);
            tercerCampo.setVisible(true);
            tresIzquierda.setVisible(true);
            tresDerecha.setVisible(true);
            setSize(360, 400);
        } else if (!campoCuatro.isVisible()) {
            campoCuatro.setVisible(true);
            cuartoCampo.setVisible(true);
            cuatroIzquierda.setVisible(true);
            cuatroDerecha.setVisible(true);
            setSize(360, 425);
        } else if (!campoCinco.isVisible()) {
            campoCinco.setVisible(true);
            quintoCampo.setVisible(true);
            cincoIzquierda.setVisible(true);
            cincoDerecha.setVisible(true);
            setSize(360, 450);
        } else if (!campoSeis.isVisible()) {
            campoSeis.setVisible(true);
            sextoCampo.setVisible(true);
            seisIzquierda.setVisible(true);
            seisDerecha.setVisible(true);
            setSize(360, 475);
        } else if (!campoSiete.isVisible()) {
            campoSiete.setVisible(true);
            septimoCampo.setVisible(true);
            sieteIzquierda.setVisible(true);
            sieteDerecha.setVisible(true);
            setSize(360, 500);
        } else if (!campoOcho.isVisible()) {
            campoOcho.setVisible(true);
            octavoCampo.setVisible(true);
            ochoIzquierda.setVisible(true);
            ochoDerecha.setVisible(true);
            setSize(360, 525);
        } else if (!campoNueve.isVisible()) {
            campoNueve.setVisible(true);
            novenoCampo.setVisible(true);
            nueveIzquierda.setVisible(true);
            nueveDerecha.setVisible(true);
            setSize(360, 550);
        } else if (!campoDiez.isVisible()) {
            campoDiez.setVisible(true);
            decimoCampo.setVisible(true);
            diezIzquierda.setVisible(true);
            diezDerecha.setVisible(true);
            setSize(360, 575);
        }
        
    }//GEN-LAST:event_bajarUnoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        campoDos.setVisible(false);
        segundoCampo.setVisible(false);
        dosIzquierda.setVisible(false);
        dosDerecha.setVisible(false);
        campoTres.setVisible(false);
        tercerCampo.setVisible(false);
        tresIzquierda.setVisible(false);
        tresDerecha.setVisible(false);
        campoCuatro.setVisible(false);
        cuartoCampo.setVisible(false);
        cuatroIzquierda.setVisible(false);
        cuatroDerecha.setVisible(false);
        campoCinco.setVisible(false);
        quintoCampo.setVisible(false);
        cincoIzquierda.setVisible(false);
        cincoDerecha.setVisible(false);
        campoSeis.setVisible(false);
        sextoCampo.setVisible(false);
        seisIzquierda.setVisible(false);
        seisDerecha.setVisible(false);
        campoSiete.setVisible(false);
        septimoCampo.setVisible(false);
        sieteIzquierda.setVisible(false);
        sieteDerecha.setVisible(false);
        campoOcho.setVisible(false);
        octavoCampo.setVisible(false);
        ochoIzquierda.setVisible(false);
        ochoDerecha.setVisible(false);
        campoNueve.setVisible(false);
        novenoCampo.setVisible(false);
        nueveIzquierda.setVisible(false);
        nueveDerecha.setVisible(false);
        campoDiez.setVisible(false);
        decimoCampo.setVisible(false);
        diezIzquierda.setVisible(false);
        diezDerecha.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void subirUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirUnoActionPerformed
       if (campoDiez.isVisible()) {
            campoDiez.setVisible(false);
            decimoCampo.setVisible(false);
            diezIzquierda.setVisible(false);
            diezDerecha.setVisible(false);
            setSize(360, 550);
        } else if (campoNueve.isVisible()) {
            campoNueve.setVisible(false);
            novenoCampo.setVisible(false);
            nueveIzquierda.setVisible(false);
            nueveDerecha.setVisible(false);
            setSize(360, 525);
        } else if (campoOcho.isVisible()) {
            campoOcho.setVisible(false);
            octavoCampo.setVisible(false);
            ochoIzquierda.setVisible(false);
            ochoDerecha.setVisible(false);
            setSize(360, 500);
        } else if (campoSiete.isVisible()) {
            campoSiete.setVisible(false);
            septimoCampo.setVisible(false);
            sieteIzquierda.setVisible(false);
            sieteDerecha.setVisible(false);
            setSize(360, 475);
        } else if (campoSeis.isVisible()) {
            campoSeis.setVisible(false);
            sextoCampo.setVisible(false);
            seisIzquierda.setVisible(false);
            seisDerecha.setVisible(false);
            setSize(360, 450);
        } else if (campoCinco.isVisible()) {
            campoCinco.setVisible(false);
            quintoCampo.setVisible(false);
            cincoIzquierda.setVisible(false);
            cincoDerecha.setVisible(false);
            setSize(360, 425);
        } else if (campoCuatro.isVisible()) {
            campoCuatro.setVisible(false);
            cuartoCampo.setVisible(false);
            cuatroIzquierda.setVisible(false);
            cuatroDerecha.setVisible(false);
            setSize(360, 400);
        } else if (campoTres.isVisible()) {
            campoTres.setVisible(false);
            tercerCampo.setVisible(false);
            tresIzquierda.setVisible(false);
            tresDerecha.setVisible(false);
            setSize(360, 375);
        } else if (campoDos.isVisible()) {
            campoDos.setVisible(false);
            segundoCampo.setVisible(false);
            dosIzquierda.setVisible(false);
            dosDerecha.setVisible(false);
            setSize(360, 350);
        }  
    }//GEN-LAST:event_subirUnoActionPerformed

    private void textoCreadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCreadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCreadoActionPerformed

    private void cuatroDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroDerechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuatroDerechaActionPerformed

    private void etiquetaVaciaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_etiquetaVaciaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_etiquetaVaciaAncestorAdded

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("resources/Icono.png"));

        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            // UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (Exception e) {
            //e.printStackTrace();
        }
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Replacer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu acercaDe;
    private javax.swing.JMenuItem acercaDeMenu;
    private javax.swing.JFrame acercaDeReplacer;
    private javax.swing.JMenu archivo;
    private javax.swing.JButton bajarUno;
    private javax.swing.JToolBar barra;
    private javax.swing.ButtonGroup barraGrupo;
    private javax.swing.JToggleButton borrarTodo;
    private javax.swing.JButton campoCinco;
    private javax.swing.JButton campoCuatro;
    private javax.swing.JButton campoDiez;
    private javax.swing.JButton campoDos;
    private javax.swing.JButton campoNueve;
    private javax.swing.JButton campoOcho;
    private javax.swing.JButton campoSeis;
    private javax.swing.JButton campoSiete;
    private javax.swing.JButton campoTres;
    private javax.swing.JButton campoUno;
    private javax.swing.JLabel cargado;
    private javax.swing.JMenuItem cargar;
    private javax.swing.JButton cargarBarra;
    private javax.swing.JTextField cincoDerecha;
    private javax.swing.JTextField cincoIzquierda;
    private javax.swing.JMenuItem contenido;
    private javax.swing.JLabel creacionTotal;
    private javax.swing.JLabel creado;
    private javax.swing.JLabel creador;
    private javax.swing.JLabel cuartoCampo;
    private javax.swing.JTextField cuatroDerecha;
    private javax.swing.JTextField cuatroIzquierda;
    private javax.swing.JLabel decimoCampo;
    private javax.swing.JTextField diezDerecha;
    private javax.swing.JTextField diezIzquierda;
    private javax.swing.JTextField dosDerecha;
    private javax.swing.JTextField dosIzquierda;
    private javax.swing.JLabel etiquetaVacia;
    private javax.swing.JLabel iconoApp;
    private javax.swing.JLabel imagenCC;
    private javax.swing.JLabel imagenReplacer;
    private javax.swing.JPanel interior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel licencia;
    private javax.swing.JLabel novenoCampo;
    private javax.swing.JTextField nueveDerecha;
    private javax.swing.JTextField nueveIzquierda;
    private javax.swing.JButton nuevo;
    private javax.swing.JMenuItem nuevoMenu;
    private javax.swing.JTextField ochoDerecha;
    private javax.swing.JTextField ochoIzquierda;
    private javax.swing.JLabel octavoCampo;
    private javax.swing.JLabel primerCampo;
    private javax.swing.JLabel quintoCampo;
    private javax.swing.JButton reemplazar;
    private javax.swing.JLabel replacer;
    private javax.swing.JMenuItem salir;
    private javax.swing.JLabel segundoCampo;
    private javax.swing.JTextField seisDerecha;
    private javax.swing.JTextField seisIzquierda;
    private javax.swing.JFileChooser selectorFicheroCargado;
    private javax.swing.JSeparator separador;
    private javax.swing.JPopupMenu.Separator separadorMenu;
    private javax.swing.JPopupMenu.Separator separadorMenu2;
    private javax.swing.JLabel septimoCampo;
    private javax.swing.JLabel sextoCampo;
    private javax.swing.JTextField sieteDerecha;
    private javax.swing.JTextField sieteIzquierda;
    private javax.swing.JButton subirUno;
    private javax.swing.JLabel tercerCampo;
    private javax.swing.JFormattedTextField textoCargado;
    private javax.swing.JFormattedTextField textoCreado;
    private javax.swing.JTextField tresDerecha;
    private javax.swing.JTextField tresIzquierda;
    private javax.swing.JTextField unoDerecha;
    private javax.swing.JTextField unoIzquierda;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables

    public int getContador() {
        return contador;
    }

    public void setContador(int contador) {
        this.contador = contador;
    }
}
